import { DhikrItem } from '../types';

export const DHIKR_ITEMS: DhikrItem[] = [
  {
    id: 'dhikr_subhanallah',
    category: 'general',
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'SubḥānAllāh',
    translation: 'Glory be to Allah',
    recommendedCount: 33,
    benefit: 'Purifies the heart and earns great reward in the sight of Allah.',
    sourceReference: 'Sahih Muslim 597',
  },
  {
    id: 'dhikr_alhamdulillah',
    category: 'gratitude',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alḥamdulillāh',
    translation: 'All praise is due to Allah',
    recommendedCount: 33,
    benefit: 'Fills the divine scales with good deeds.',
    sourceReference: 'Sahih Muslim 223',
  },
  {
    id: 'dhikr_allahuakbar',
    category: 'general',
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allāhu Akbar',
    translation: 'Allah is the Greatest',
    recommendedCount: 34,
    benefit: 'Affirms that Allah is greater than every worldly distraction and hardship.',
    sourceReference: 'Sahih al-Bukhari 3113',
  },
  {
    id: 'dhikr_la_ilaha_illallah',
    category: 'peace',
    arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ',
    transliteration: 'Lā ilāha illallāh',
    translation: 'There is no deity worthy of worship except Allah',
    recommendedCount: 100,
    benefit: 'The greatest statement of Tawheed (monotheism) and the key to Paradise.',
    sourceReference: 'At-Tirmidhi 3383',
  },
  {
    id: 'dhikr_astaghfirullah',
    category: 'repentance',
    arabic: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
    transliteration: 'Astaghfirullāha wa atūbu ilayh',
    translation: 'I seek Allah\'s forgiveness and repent to Him',
    recommendedCount: 100,
    benefit: 'Opens the doors of divine mercy, relief from sorrow, and provision from unexpected sources.',
    sourceReference: 'Sahih al-Bukhari 6307',
  },
  {
    id: 'dhikr_salawat',
    category: 'friday',
    arabic: 'اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ',
    transliteration: 'Allāhumma ṣalli \'alā Muḥammadin wa \'alā āli Muḥammad',
    translation: 'O Allah, bestow peace and blessings upon Muhammad and the family of Muhammad',
    recommendedCount: 10,
    benefit: 'Whoever sends blessings upon the Prophet once, Allah will send blessings upon them tenfold.',
    sourceReference: 'Sahih Muslim 408',
  },
  {
    id: 'dhikr_tashahhud_subhanallahi_wa_bihamdihi',
    category: 'morning',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ ، سُبْحَانَ اللَّهِ الْعَظِيمِ',
    transliteration: 'SubḥānAllāhi wa biḥamdih, SubḥānAllāhil-\'Aẓīm',
    translation: 'Glory be to Allah and His is the praise; Glory be to Allah, the Supreme',
    recommendedCount: 100,
    benefit: 'Two phrases light on the tongue, heavy on the scales, beloved to the Most Merciful.',
    sourceReference: 'Sahih al-Bukhari 6406',
  },
  {
    id: 'dhikr_la_hawla',
    category: 'protection',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Lā ḥawla wa lā quwwata illā billāh',
    translation: 'There is no power and no strength except with Allah',
    recommendedCount: 33,
    benefit: 'One of the treasures of Jannah (Paradise). Removes anxiety and despair.',
    sourceReference: 'Sahih al-Bukhari 4205',
  },
  {
    id: 'dhikr_hasbunallah',
    category: 'peace',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'ḤasbunAllāhu wa ni\'mal-Wakīl',
    translation: 'Allah is sufficient for us, and He is the best Disposer of affairs',
    recommendedCount: 33,
    benefit: 'The powerful statement uttered by Prophet Ibrahim (AS) and Prophet Muhammad (ﷺ) in adversity.',
    sourceReference: 'Surah Ali \'Imran 3:173, Sahih al-Bukhari 4563',
  },
  {
    id: 'dhikr_subhanallahi_wa_bihamdihi_adada',
    category: 'morning',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ',
    transliteration: 'SubḥānAllāhi wa biḥamdihi \'adada khalqih, wa riḍā nafsih, wa zinata \'arshih, wa midāda kalimātih',
    translation: 'Glory and praise be to Allah as much as the number of His creation, according to His pleasure, by the weight of His Throne, and by the ink of His words',
    recommendedCount: 3,
    benefit: 'Weighs heavier than hours of continuous remembrance.',
    sourceReference: 'Sahih Muslim 2726',
  },
];
