import { DuaItem } from '../types';

export const DUAS_LIST: DuaItem[] = [
  {
    id: 'dua_morning_waking',
    category: 'morning',
    title: 'Upon Waking Up',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alḥamdu lillāhillaḏhī aḥyānā ba\'da mā amātanā wa ilayhin-nushūr',
    translation: 'All praise is for Allah who gave us life after having given us death, and unto Him is the resurrection.',
    reference: 'Sahih al-Bukhari 6312',
  },
  {
    id: 'dua_anxiety_relief',
    category: 'anxiety',
    title: 'Dua for Anxiety & Distress',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ ، وَالْعَجْزِ وَالْكَسَلِ ، وَالْبُخْلِ وَالْجُبْنِ ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    transliteration: 'Allāhumma innī a\'ūdhu bika minal-hammi wal-ḥazan, wal-\'ajzi wal-kasal, wal-bukhli wal-jubn, wa ḍala\'id-dayni wa ghalabatir-rijāl',
    translation: 'O Allah, I seek refuge in You from grief and sadness, from weakness and laziness, from miserliness and cowardice, from being heavily in debt and being overcome by men.',
    reference: 'Sahih al-Bukhari 2893',
  },
  {
    id: 'dua_parents',
    category: 'parents',
    title: 'Dua for Parents',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: 'Rabbir-ḥamhumā kamā rabbayānī ṣaghīrā',
    translation: 'My Lord, have mercy upon them as they brought me up [when I was] small.',
    reference: 'Surah Al-Isra 17:24',
  },
  {
    id: 'dua_forgiveness_sayyidul_istighfar',
    category: 'forgiveness',
    title: 'Sayyidul Istighfar (Master of Forgiveness)',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ ، خَلَقْتَنِي وَأَنَا عَبْدُكَ ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allāhumma Anta Rabbī lā ilāha illā Ant, khalaqtanī wa anā \'abduk, wa anā \'alā \'ahdika wa wa\'dika mastaṭa\'t, a\'ūdhu bika min sharri mā ṣana\'t, abū\'u laka bini\'matika \'alayy, wa abū\'u laka bidhanbī faghfir lī fainnahū lā yaghfirudh-dhunūba illā Ant.',
    translation: 'O Allah, You are my Lord, there is no deity except You. You created me and I am Your servant, and I abide by Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me, and I acknowledge my sin, so forgive me, for none forgives sins except You.',
    reference: 'Sahih al-Bukhari 6306',
  },
  {
    id: 'dua_knowledge',
    category: 'knowledge',
    title: 'Dua for Beneficial Knowledge',
    arabic: 'رَّبِّ زِدْنِي عِلْمًا',
    transliteration: 'Rabbi zidnī \'ilmā',
    translation: 'My Lord, increase me in knowledge.',
    reference: 'Surah Taha 20:114',
  },
  {
    id: 'dua_leaving_home',
    category: 'travel',
    title: 'When Leaving the Home',
    arabic: 'بِسْمِ اللَّهِ ، تَوَكَّلْتُ عَلَى اللَّهِ ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Bismillāh, tawakkaltu \'alallāh, wa lā ḥawla wa lā quwwata illā billāh',
    translation: 'In the name of Allah, I place my trust in Allah; there is no power and no strength except with Allah.',
    reference: 'Abu Dawud 5095, At-Tirmidhi 3426',
  },
  {
    id: 'dua_protection_evil',
    category: 'protection',
    title: 'Protection from All Harm',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillāhillaḏhī lā yaḍurru ma\'as-mihī shay\'un fil-arḍi wa lā fis-samā\'i wa Huwas-Samī\'ul-\'Alīm',
    translation: 'In the name of Allah, with whose name nothing on earth or in the heavens can cause harm, and He is the All-Hearing, the All-Knowing.',
    reference: 'Abu Dawud 5088, At-Tirmidhi 3388',
  },
  {
    id: 'dua_before_sleep',
    category: 'sleep',
    title: 'Before Sleeping',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allāhumma amūtu wa aḥyā',
    translation: 'In Your name, O Allah, I die and I live.',
    reference: 'Sahih al-Bukhari 6324',
  },
  {
    id: 'dua_ramadan_iftar',
    category: 'ramadan',
    title: 'At the Time of Breaking the Fast (Iftar)',
    arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ',
    transliteration: 'Dhahabadh-dhama\'u wabtallatil-\'urūqu wa thabatal-ajru in shā\'Allāh',
    translation: 'The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
    reference: 'Sunan Abi Dawud 2357 (Sahih al-Albani)',
  },
  {
    id: 'dua_good_in_both_worlds',
    category: 'daily',
    title: 'Dua for Good in This Life and Hereafter',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Rabbanā ātinā fid-dunyā ḥasanatan wa fil-ākhirati ḥasanatan wa qinā \'adhāban-nār',
    translation: 'Our Lord, grant us good in this world and good in the Hereafter, and save us from the punishment of the Fire.',
    reference: 'Surah Al-Baqarah 2:201',
  },
  {
    id: 'dua_entering_mosque',
    category: 'daily',
    title: 'Entering the Mosque',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: 'Allāhummaf-taḥ lī abwāba raḥmatik',
    translation: 'O Allah, open the gates of Your mercy for me.',
    reference: 'Sahih Muslim 713',
  },
  {
    id: 'dua_leaving_mosque',
    category: 'daily',
    title: 'Leaving the Mosque',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: 'Allāhumma innī as\'aluka min faḍlik',
    translation: 'O Allah, I ask You from Your bounty.',
    reference: 'Sahih Muslim 713',
  },
  {
    id: 'dua_before_eating',
    category: 'daily',
    title: 'Before Eating',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillāh',
    translation: 'In the name of Allah.',
    reference: 'Sahih al-Bukhari 5376',
  },
  {
    id: 'dua_after_eating',
    category: 'daily',
    title: 'After Finishing a Meal',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: 'Alḥamdu lillāhillaḏhī aṭ\'amanā wa saqānā wa ja\'alanā muslimīn',
    translation: 'Praise be to Allah who has fed us, given us drink, and made us Muslims.',
    reference: 'Abu Dawud 3850, At-Tirmidhi 3457',
  },
  {
    id: 'dua_steadfast_heart',
    category: 'forgiveness',
    title: 'For Steadfastness in Faith',
    arabic: 'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ',
    transliteration: 'Yā Muqallibal-qulūbi thabbit qalbī \'alā dīnik',
    translation: 'O Turner of the hearts, keep my heart firm upon Your religion.',
    reference: 'Jami\' at-Tirmidhi 2140 (Sahih)',
  },
  {
    id: 'dua_ease_difficulty',
    category: 'anxiety',
    title: 'When Facing Hardship or Difficulty',
    arabic: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا',
    transliteration: 'Allāhumma lā sahla illā mā ja\'altahū sahlā, wa Anta taj\'alul-ḥazna idhā shi\'ta sahlā',
    translation: 'O Allah, there is no ease except that which You make easy, and You can make distress easy if You wish.',
    reference: 'Sahih Ibn Hibban 327',
  },
  {
    id: 'dua_debt_relief',
    category: 'anxiety',
    title: 'Dua for Debt Relief & Freedom from Stress',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: 'Allāhummak-finī bi-ḥalālika \'an ḥarāmika wa aghninī bi-faḍlika \'amman siwāk',
    translation: 'O Allah, suffice me with what You have made lawful against what You have made unlawful, and enrich me by Your grace from anyone other than You.',
    reference: 'Jami\' at-Tirmidhi 3563 (Hasan)',
  },
  {
    id: 'dua_visiting_sick',
    category: 'protection',
    title: 'When Visiting the Sick',
    arabic: 'لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ',
    transliteration: 'Lā ba\'sa ṭahūrun in shā\'Allāh',
    translation: 'Do not worry, it is a purification [from sins], if Allah wills.',
    reference: 'Sahih al-Bukhari 3616',
  },
  {
    id: 'dua_istikhara',
    category: 'knowledge',
    title: 'Supplication for Divine Guidance (Istikhara)',
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ',
    transliteration: 'Allāhumma innī astakhīruka bi-\'ilmik, wa astaqdiruka bi-qudratik, wa as\'aluka min faḍlikal-\'aẓīm',
    translation: 'O Allah, I seek Your guidance by virtue of Your knowledge, and I seek ability by virtue of Your power, and I ask You of Your great bounty.',
    reference: 'Sahih al-Bukhari 1166',
  },
];
