import { HadithItem } from '../types';

export const HADITH_ITEMS: HadithItem[] = [
  {
    id: 'hadith_intentions',
    category: 'faith',
    arabic: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    transliteration: "Innama al-a'malu bin-niyyat, wa innama li-kulli imri'in ma nawa",
    narrator: 'Narrated Umar bin al-Khattab (RA)',
    translation: 'Actions are judged by intentions, and every person will get the reward according to what was intended.',
    collection: 'Sahih al-Bukhari',
    book: 'Book of Revelation',
    hadithNumber: '1',
    grade: 'Sahih (Muttafaq \'Alayh / Agreed Upon)',
    source: 'Sahih al-Bukhari 1, Sahih Muslim 1907',
    keyLesson: 'Sincerity (Ikhlas) is the foundational requirement for every deed to be accepted by Allah.',
  },
  {
    id: 'hadith_mercy_creation',
    category: 'mercy',
    arabic: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ ، ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
    transliteration: 'Ar-rahimuna yarhamuhumu ar-Rahman, irhamu man fil-ardi yarhamkum man fis-sama\'',
    narrator: 'Narrated Abdullah ibn Amr (RA)',
    translation: 'The merciful will be shown mercy by the Most Merciful. Be merciful to those on earth and the One in the heavens will have mercy upon you.',
    collection: 'Jami\' at-Tirmidhi',
    book: 'Chapters on Righteousness and Maintaining Ties',
    hadithNumber: '1924',
    grade: 'Sahih (Authentic)',
    source: 'At-Tirmidhi 1924, Abu Dawud 4941',
    keyLesson: 'Universal compassion towards all beings attracts the limitless mercy of the Creator.',
  },
  {
    id: 'hadith_good_character',
    category: 'character',
    arabic: 'إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ وَأَقْرَبِكُمْ مِنِّي مَجْلِسًا يَوْمَ الْقِيَامَةِ أَحَاسِنَكُمْ أَخْلاَقًا',
    transliteration: "Inna min ahabbi-kum ilayya wa aqrabi-kum minni majlisan yawm al-qiyamati ahsanakum akhlaqa",
    narrator: 'Narrated Jabir ibn Abdullah (RA)',
    translation: 'Verily, the most beloved of you to me and the closest of you to me on the Day of Resurrection are those with the best character.',
    collection: 'Jami\' at-Tirmidhi',
    book: 'Chapters on Righteousness',
    hadithNumber: '2018',
    grade: 'Sahih',
    source: 'At-Tirmidhi 2018',
    keyLesson: 'Noble character and gentle manners elevate a believer to the highest ranks near the Prophet (ﷺ).',
  },
  {
    id: 'hadith_patience_affliction',
    category: 'patience',
    arabic: 'مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلاَ وَصَبٍ وَلاَ هَمٍّ وَلاَ حُزْنٍ وَلاَ أَذًى وَلاَ غَمٍّ حَتَّى الشَّوْكَةِ يُشَاكُهَا إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ',
    transliteration: "Ma yusibu al-muslima min nasabin wa la wasabin wa la hammin wa la huznin wa la adhan wa la ghammin hatta ash-shawkati yushakuha illa kaffarAllahu biha min khatayahu",
    narrator: 'Narrated Abu Huraira & Abu Sa\'id al-Khudri (RA)',
    translation: 'No fatigue, illness, worry, sorrow, harm or distress afflicts a Muslim, even the prick of a thorn, except that Allah expiates some of their sins thereby.',
    collection: 'Sahih al-Bukhari',
    book: 'Book of Patients',
    hadithNumber: '5641',
    grade: 'Sahih (Muttafaq \'Alayh)',
    source: 'Sahih al-Bukhari 5641, Sahih Muslim 2573',
    keyLesson: 'Every pain or mental burden endured patiently serves as a spiritual purification and elevation.',
  },
  {
    id: 'hadith_smile_charity',
    category: 'charity',
    arabic: 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
    transliteration: 'Tabassumuka fi wajhi akhika laka sadaqah',
    narrator: 'Narrated Abu Dharr (RA)',
    translation: 'Your smiling in the face of your brother or sister is an act of charity.',
    collection: 'Jami\' at-Tirmidhi',
    book: 'Chapters on Righteousness',
    hadithNumber: '1956',
    grade: 'Hasan Sahih',
    source: 'At-Tirmidhi 1956',
    keyLesson: 'Spreading warmth, kindness, and positivity carries the spiritual weight of financial giving.',
  },
  {
    id: 'hadith_seek_knowledge',
    category: 'knowledge',
    arabic: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
    transliteration: "Man salaka tariqan yaltamisu fihi 'ilman sahhala Allahu lahu bihi tariqan ila al-Jannah",
    narrator: 'Narrated Abu Huraira (RA)',
    translation: 'Whoever treads a path in pursuit of knowledge, Allah makes easy for him a path to Paradise.',
    collection: 'Sahih Muslim',
    book: 'Book of Knowledge',
    hadithNumber: '2699',
    grade: 'Sahih',
    source: 'Sahih Muslim 2699',
    keyLesson: 'Continuous learning and seeking sacred knowledge is an illuminated stairway to Jannah.',
  },
  {
    id: 'hadith_prayer_coolness',
    category: 'prayer',
    arabic: 'وَجُعِلَتْ قُرَّةُ عَيْنِي فِي الصَّلاَةِ',
    transliteration: "Wa ju'ilat qurratu 'ayni fis-Salah",
    narrator: 'Narrated Anas bin Malik (RA)',
    translation: 'And the true comfort and coolness of my eyes was placed in the Prayer (Salah).',
    collection: 'Sunan an-Nasa\'i',
    book: 'The Book of the Kind Treatment of Women',
    hadithNumber: '3939',
    grade: 'Hasan Sahih',
    source: 'An-Nasa\'i 3939, Musnad Ahmad 12293',
    keyLesson: 'Prayer is not merely an obligation; it is a sacred sanctuary of peace for the restless soul.',
  },
  {
    id: 'hadith_gratitude_people',
    category: 'gratitude',
    arabic: 'لاَ يَشْكُرُ اللَّهَ مَنْ لاَ يَشْكُرُ النَّاسَ',
    transliteration: 'La yashkuru Allaha man la yashkuru an-nas',
    narrator: 'Narrated Abu Huraira (RA)',
    translation: 'Whoever does not thank people does not thank Allah.',
    collection: 'Sunan Abi Dawud',
    book: 'General Behavior',
    hadithNumber: '4811',
    grade: 'Sahih',
    source: 'Abu Dawud 4811, At-Tirmidhi 1954',
    keyLesson: 'True gratitude to Allah is demonstrated by expressing humble appreciation to people who help you.',
  },
  {
    id: 'hadith_purity_faith',
    category: 'faith',
    arabic: 'الطُّهُورُ شَطْرُ الإِيمَانِ ، وَالْحَمْدُ لِلَّهِ تَمْلأُ الْمِيزَانَ',
    transliteration: 'At-tuhuru shatru al-iman, wal-hamdu lillahi tamla\'ul-mizan',
    narrator: 'Narrated Abu Malik al-Ash\'ari (RA)',
    translation: 'Purity is half of faith, and "Alhamdulillah" (all praise is due to Allah) fills the scale.',
    collection: 'Sahih Muslim',
    book: 'Book of Purification',
    hadithNumber: '223',
    grade: 'Sahih',
    source: 'Sahih Muslim 223',
    keyLesson: 'Inner spiritual cleanliness and outer physical cleanliness are deeply woven into sound faith.',
  },
  {
    id: 'hadith_love_brother',
    category: 'character',
    arabic: 'لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    transliteration: 'La yu\'minu ahadukum hatta yuhibba li-akhihi ma yuhibbu li-nafsih',
    narrator: 'Narrated Anas bin Malik (RA)',
    translation: 'None of you truly believes until he loves for his brother [in humanity] what he loves for himself.',
    collection: 'Sahih al-Bukhari',
    book: 'Book of Faith',
    hadithNumber: '13',
    grade: 'Sahih (Muttafaq \'Alayh)',
    source: 'Sahih al-Bukhari 13, Sahih Muslim 45',
    keyLesson: 'Selflessness and desiring goodness for others is an indispensable pillar of authentic belief.',
  },
  {
    id: 'hadith_remembrance_tranquility',
    category: 'remembrance',
    arabic: 'مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَالَّذِي لاَ يَذْكُرُ رَبَّهُ مَثَلُ الْحَىِّ وَالْمَيِّتِ',
    transliteration: 'Mathalu alladhi yadhkuru Rabbahu walladhi la yadhkuru Rabbahu mathalu al-hayyi wal-mayyit',
    narrator: 'Narrated Abu Musa al-Ash\'ari (RA)',
    translation: 'The likeness of the one who remembers his Lord and the one who does not remember his Lord is like that of the living and the dead.',
    collection: 'Sahih al-Bukhari',
    book: 'Book of Invocations',
    hadithNumber: '6407',
    grade: 'Sahih',
    source: 'Sahih al-Bukhari 6407, Sahih Muslim 779',
    keyLesson: 'Dhikr (remembrance of Allah) is the breath and life of the spiritual heart.',
  },
  {
    id: 'hadith_good_speech_silence',
    category: 'character',
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    transliteration: "Man kana yu'minu billahi wal-yawmil-akhiri fal-yaqul khayran aw li-yasmut",
    narrator: 'Narrated Abu Huraira (RA)',
    translation: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
    collection: 'Sahih al-Bukhari',
    book: 'Book of Good Manners',
    hadithNumber: '6018',
    grade: 'Sahih (Muttafaq \'Alayh)',
    source: 'Sahih al-Bukhari 6018, Sahih Muslim 47',
    keyLesson: 'Guarding one\'s speech and practicing restraint prevents sin and fosters peace.',
  },
  {
    id: 'hadith_best_quran',
    category: 'knowledge',
    arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    transliteration: "Khayrukum man ta'allama al-Qur'ana wa 'allamahu",
    narrator: 'Narrated Uthman bin Affan (RA)',
    translation: 'The best among you are those who learn the Qur\'an and teach it to others.',
    collection: 'Sahih al-Bukhari',
    book: 'Virtues of the Qur\'an',
    hadithNumber: '5027',
    grade: 'Sahih',
    source: 'Sahih al-Bukhari 5027',
    keyLesson: 'Devoting time to understanding and passing on the Divine Revelation is the highest calling.',
  },
  {
    id: 'hadith_ease_religion',
    category: 'faith',
    arabic: 'إِنَّ الدِّينَ يُسْرٌ ، وَلَنْ يُشَادَّ الدِّينَ أَحَدٌ إِلاَّ غَلَبَهُ',
    transliteration: 'Inna ad-deena yusrun, wa lan yushadda ad-deena ahadun illa ghalabahu',
    narrator: 'Narrated Abu Huraira (RA)',
    translation: 'Indeed, religion is ease, and no one overburdens himself in the religion except that it will overcome him.',
    collection: 'Sahih al-Bukhari',
    book: 'Book of Faith',
    hadithNumber: '39',
    grade: 'Sahih',
    source: 'Sahih al-Bukhari 39',
    keyLesson: 'Consistency and moderation in worship surpass extreme, unsustainable burdens.',
  },
  {
    id: 'hadith_two_light_words',
    category: 'remembrance',
    arabic: 'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ ، ثَقِيلَتَانِ فِي الْمِيزَانِ ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ : سُبْحَانَ اللَّهِ وَبِحَمْدِهِ ، سُبْحَانَ اللَّهِ الْعَظِيمِ',
    transliteration: "Kalimatani khafifatani 'alal-lisan, thaqilatani fil-mizan, habibatani ila ar-Rahman: Subhan Allahi wa bihamdih, Subhan Allahil-'Azim",
    narrator: 'Narrated Abu Huraira (RA)',
    translation: 'Two phrases are light on the tongue, heavy on the Scales, and beloved to the Most Merciful: "Subhan Allahi wa bi-hamdih, Subhan Allahil-\'Azim" (Glory be to Allah and His is the praise, Glory be to Allah the Tremendous).',
    collection: 'Sahih al-Bukhari',
    book: 'Book of Invocations',
    hadithNumber: '6406',
    grade: 'Sahih (Muttafaq \'Alayh)',
    source: 'Sahih al-Bukhari 6406, Sahih Muslim 2694',
    keyLesson: 'Simple, heartfelt dhikr can yield immeasurable reward on the Day of Reckoning.',
  },
];
