import { JuzInfo } from '../types';

export const JUZ_LIST: JuzInfo[] = [
  {
    juzNumber: 1,
    nameArabic: 'الم',
    nameTransliteration: 'Alif Lām Mīm',
    startSurahNumber: 1,
    startSurahName: 'Al-Fatihah',
    startAyahNumber: 1,
    endSurahNumber: 2,
    endSurahName: 'Al-Baqarah',
    endAyahNumber: 141,
  },
  {
    juzNumber: 2,
    nameArabic: 'سَيَقُولُ',
    nameTransliteration: 'Sayaqūl',
    startSurahNumber: 2,
    startSurahName: 'Al-Baqarah',
    startAyahNumber: 142,
    endSurahNumber: 2,
    endSurahName: 'Al-Baqarah',
    endAyahNumber: 252,
  },
  {
    juzNumber: 3,
    nameArabic: 'تِلْكَ الرُّسُلُ',
    nameTransliteration: 'Tilkar-Rusul',
    startSurahNumber: 2,
    startSurahName: 'Al-Baqarah',
    startAyahNumber: 253,
    endSurahNumber: 3,
    endSurahName: 'Ali \'Imran',
    endAyahNumber: 92,
  },
  {
    juzNumber: 4,
    nameArabic: 'لَن تَنَالُوا',
    nameTransliteration: 'Lan Tanālū',
    startSurahNumber: 3,
    startSurahName: 'Ali \'Imran',
    startAyahNumber: 93,
    endSurahNumber: 4,
    endSurahName: 'An-Nisa',
    endAyahNumber: 23,
  },
  {
    juzNumber: 5,
    nameArabic: 'وَالْمُحْصَنَاتُ',
    nameTransliteration: 'Wal-Muḥṣanāt',
    startSurahNumber: 4,
    startSurahName: 'An-Nisa',
    startAyahNumber: 24,
    endSurahNumber: 4,
    endSurahName: 'An-Nisa',
    endAyahNumber: 147,
  },
  {
    juzNumber: 6,
    nameArabic: 'لَا يُحِبُّ اللَّهُ',
    nameTransliteration: 'Lā Yuḥibbullāh',
    startSurahNumber: 4,
    startSurahName: 'An-Nisa',
    startAyahNumber: 148,
    endSurahNumber: 5,
    endSurahName: 'Al-Ma\'idah',
    endAyahNumber: 81,
  },
  {
    juzNumber: 7,
    nameArabic: 'وَإِذَا سَمِعُوا',
    nameTransliteration: 'Wa Idhā Sami\'ū',
    startSurahNumber: 5,
    startSurahName: 'Al-Ma\'idah',
    startAyahNumber: 82,
    endSurahNumber: 6,
    endSurahName: 'Al-An\'am',
    endAyahNumber: 110,
  },
  {
    juzNumber: 8,
    nameArabic: 'وَلَوْ أَنَّنَا',
    nameTransliteration: 'Wa Law Annanā',
    startSurahNumber: 6,
    startSurahName: 'Al-An\'am',
    startAyahNumber: 111,
    endSurahNumber: 7,
    endSurahName: 'Al-A\'raf',
    endAyahNumber: 87,
  },
  {
    juzNumber: 9,
    nameArabic: 'قَالَ الْمَلَأُ',
    nameTransliteration: 'Qālal-Mala\'u',
    startSurahNumber: 7,
    startSurahName: 'Al-A\'raf',
    startAyahNumber: 88,
    endSurahNumber: 8,
    endSurahName: 'Al-Anfal',
    endAyahNumber: 40,
  },
  {
    juzNumber: 10,
    nameArabic: 'وَاعْلَمُوا',
    nameTransliteration: 'Wa\'lamū',
    startSurahNumber: 8,
    startSurahName: 'Al-Anfal',
    startAyahNumber: 41,
    endSurahNumber: 9,
    endSurahName: 'At-Tawbah',
    endAyahNumber: 92,
  },
  {
    juzNumber: 11,
    nameArabic: 'يَعْتَذِرُونَ',
    nameTransliteration: 'Ya\'tadhirūn',
    startSurahNumber: 9,
    startSurahName: 'At-Tawbah',
    startAyahNumber: 93,
    endSurahNumber: 11,
    endSurahName: 'Hud',
    endAyahNumber: 5,
  },
  {
    juzNumber: 12,
    nameArabic: 'وَمَا مِن دَابَّةٍ',
    nameTransliteration: 'Wa Mā Min Dābbatin',
    startSurahNumber: 11,
    startSurahName: 'Hud',
    startAyahNumber: 6,
    endSurahNumber: 12,
    endSurahName: 'Yusuf',
    endAyahNumber: 52,
  },
  {
    juzNumber: 13,
    nameArabic: 'وَمَا أُبَرِّئُ',
    nameTransliteration: 'Wa Mā Ubarri\'u',
    startSurahNumber: 12,
    startSurahName: 'Yusuf',
    startAyahNumber: 53,
    endSurahNumber: 14,
    endSurahName: 'Ibrahim',
    endAyahNumber: 52,
  },
  {
    juzNumber: 14,
    nameArabic: 'رُبَمَا',
    nameTransliteration: 'Rubamā',
    startSurahNumber: 15,
    startSurahName: 'Al-Hijr',
    startAyahNumber: 1,
    endSurahNumber: 16,
    endSurahName: 'An-Nahl',
    endAyahNumber: 128,
  },
  {
    juzNumber: 15,
    nameArabic: 'سُبْحَانَ الَّذِي',
    nameTransliteration: 'Subḥānalladhī',
    startSurahNumber: 17,
    startSurahName: 'Al-Isra',
    startAyahNumber: 1,
    endSurahNumber: 18,
    endSurahName: 'Al-Kahf',
    endAyahNumber: 74,
  },
  {
    juzNumber: 16,
    nameArabic: 'قَالَ أَلَمْ',
    nameTransliteration: 'Qāla Alam',
    startSurahNumber: 18,
    startSurahName: 'Al-Kahf',
    startAyahNumber: 75,
    endSurahNumber: 20,
    endSurahName: 'Taha',
    endAyahNumber: 135,
  },
  {
    juzNumber: 17,
    nameArabic: 'اقْتَرَبَ لِلنَّاسِ',
    nameTransliteration: 'Iqtaraba Lin-Nās',
    startSurahNumber: 21,
    startSurahName: 'Al-Anbiya',
    startAyahNumber: 1,
    endSurahNumber: 22,
    endSurahName: 'Al-Hajj',
    endAyahNumber: 78,
  },
  {
    juzNumber: 18,
    nameArabic: 'قَدْ أَفْلَحَ',
    nameTransliteration: 'Qad Aflaḥa',
    startSurahNumber: 23,
    startSurahName: 'Al-Mu\'minun',
    startAyahNumber: 1,
    endSurahNumber: 25,
    endSurahName: 'Al-Furqan',
    endAyahNumber: 20,
  },
  {
    juzNumber: 19,
    nameArabic: 'وَقَالَ الَّذِينَ',
    nameTransliteration: 'Wa Qālalladhīna',
    startSurahNumber: 25,
    startSurahName: 'Al-Furqan',
    startAyahNumber: 21,
    endSurahNumber: 27,
    endSurahName: 'An-Naml',
    endAyahNumber: 55,
  },
  {
    juzNumber: 20,
    nameArabic: 'أَمَّنْ خَلَقَ',
    nameTransliteration: 'Amman Khalaqa',
    startSurahNumber: 27,
    startSurahName: 'An-Naml',
    startAyahNumber: 56,
    endSurahNumber: 29,
    endSurahName: 'Al-\'Ankabut',
    endAyahNumber: 45,
  },
  {
    juzNumber: 21,
    nameArabic: 'اتْلُ مَا أُوحِيَ',
    nameTransliteration: 'Utlu Mā Ūḥiya',
    startSurahNumber: 29,
    startSurahName: 'Al-\'Ankabut',
    startAyahNumber: 46,
    endSurahNumber: 33,
    endSurahName: 'Al-Ahzab',
    endAyahNumber: 30,
  },
  {
    juzNumber: 22,
    nameArabic: 'وَمَن يَقْنُتْ',
    nameTransliteration: 'Wa Man Yaqnut',
    startSurahNumber: 33,
    startSurahName: 'Al-Ahzab',
    startAyahNumber: 31,
    endSurahNumber: 36,
    endSurahName: 'Ya-Sin',
    endAyahNumber: 27,
  },
  {
    juzNumber: 23,
    nameArabic: 'وَمَا لِيَ',
    nameTransliteration: 'Wa Mā Liya',
    startSurahNumber: 36,
    startSurahName: 'Ya-Sin',
    startAyahNumber: 28,
    endSurahNumber: 39,
    endSurahName: 'Az-Zumar',
    endAyahNumber: 31,
  },
  {
    juzNumber: 24,
    nameArabic: 'فَمَنْ أَظْلَمُ',
    nameTransliteration: 'Faman Aẓlamu',
    startSurahNumber: 39,
    startSurahName: 'Az-Zumar',
    startAyahNumber: 32,
    endSurahNumber: 41,
    endSurahName: 'Fussilat',
    endAyahNumber: 46,
  },
  {
    juzNumber: 25,
    nameArabic: 'إِلَيْهِ يُرَدُّ',
    nameTransliteration: 'Ilayhi Yuraddu',
    startSurahNumber: 41,
    startSurahName: 'Fussilat',
    startAyahNumber: 47,
    endSurahNumber: 45,
    endSurahName: 'Al-Jathiyah',
    endAyahNumber: 37,
  },
  {
    juzNumber: 26,
    nameArabic: 'حم',
    nameTransliteration: 'Ḥā Mīm',
    startSurahNumber: 46,
    startSurahName: 'Al-Ahqaf',
    startAyahNumber: 1,
    endSurahNumber: 51,
    endSurahName: 'Adh-Dhariyat',
    endAyahNumber: 30,
  },
  {
    juzNumber: 27,
    nameArabic: 'قَالَ فَمَا خَطْبُكُمْ',
    nameTransliteration: 'Qāla Famā Khaṭbukum',
    startSurahNumber: 51,
    startSurahName: 'Adh-Dhariyat',
    startAyahNumber: 31,
    endSurahNumber: 57,
    endSurahName: 'Al-Hadid',
    endAyahNumber: 29,
  },
  {
    juzNumber: 28,
    nameArabic: 'قَدْ سَمِعَ اللَّهُ',
    nameTransliteration: 'Qad Sami\'allāh',
    startSurahNumber: 58,
    startSurahName: 'Al-Mujadila',
    startAyahNumber: 1,
    endSurahNumber: 66,
    endSurahName: 'At-Tahrim',
    endAyahNumber: 12,
  },
  {
    juzNumber: 29,
    nameArabic: 'تَبَارَكَ الَّذِي',
    nameTransliteration: 'Tabārakalladhī',
    startSurahNumber: 67,
    startSurahName: 'Al-Mulk',
    startAyahNumber: 1,
    endSurahNumber: 77,
    endSurahName: 'Al-Mursalat',
    endAyahNumber: 50,
  },
  {
    juzNumber: 30,
    nameArabic: 'عَمَّ يَتَسَاءَلُونَ',
    nameTransliteration: '\'Amma Yatasā\'alūn',
    startSurahNumber: 78,
    startSurahName: 'An-Naba',
    startAyahNumber: 1,
    endSurahNumber: 114,
    endSurahName: 'An-Nas',
    endAyahNumber: 6,
  },
];
