import { AllahName } from '../types';

export const NAMES_OF_ALLAH: AllahName[] = [
  {
    number: 1,
    arabic: 'الرَّحْمَٰنُ',
    transliteration: 'Ar-Rahmān',
    meaning: 'The Entirely Merciful',
    explanation: 'He who wills goodness and mercy for all His creatures unconditionally.',
    foundInQuran: 'Surah Al-Fatihah 1:3',
  },
  {
    number: 2,
    arabic: 'الرَّحِيمُ',
    transliteration: 'Ar-Rahīm',
    meaning: 'The Especially Merciful',
    explanation: 'He who acts with boundless mercy, particularly bestowing eternal favors upon the faithful.',
    foundInQuran: 'Surah Al-Baqarah 2:163',
  },
  {
    number: 3,
    arabic: 'الْمَلِكُ',
    transliteration: 'Al-Malik',
    meaning: 'The Sovereign Lord',
    explanation: 'The supreme ruler and absolute master of the entire universe, with dominion over all existence.',
    foundInQuran: 'Surah Al-Hashr 59:23',
  },
  {
    number: 4,
    arabic: 'الْقُدُّوسُ',
    transliteration: 'Al-Quddūs',
    meaning: 'The Pure / The Most Holy',
    explanation: 'He who is free from all deficiencies, blemishes, defects, and shortcomings.',
    foundInQuran: 'Surah Al-Jumu\'ah 62:1',
  },
  {
    number: 5,
    arabic: 'السَّلَامُ',
    transliteration: 'As-Salām',
    meaning: 'The Source of Peace',
    explanation: 'The giver of security, tranquility, and safety to His creation.',
    foundInQuran: 'Surah Al-Hashr 59:23',
  },
  {
    number: 6,
    arabic: 'الْمُؤْمِنُ',
    transliteration: 'Al-Mu\'min',
    meaning: 'The Granter of Security',
    explanation: 'He who witnesses His own Oneness, inspires faith in His servants, and guarantees peace.',
    foundInQuran: 'Surah Al-Hashr 59:23',
  },
  {
    number: 7,
    arabic: 'الْمُهَيْمِنُ',
    transliteration: 'Al-Muhaymin',
    meaning: 'The Guardian / The Overseer',
    explanation: 'He who watches over, preserves, protects, and encompasses all things.',
    foundInQuran: 'Surah Al-Hashr 59:23',
  },
  {
    number: 8,
    arabic: 'الْعَزِيزُ',
    transliteration: 'Al-\'Azīz',
    meaning: 'The All-Mighty',
    explanation: 'The Invincible, whom none can overcome, possessing unassailable honor and power.',
    foundInQuran: 'Surah Ali \'Imran 3:62',
  },
  {
    number: 9,
    arabic: 'الْجَبَّارُ',
    transliteration: 'Al-Jabbār',
    meaning: 'The Compeller / The Restorer',
    explanation: 'He who mends the brokenhearted, enriches the poor, and whose decree cannot be resisted.',
    foundInQuran: 'Surah Al-Hashr 59:23',
  },
  {
    number: 10,
    arabic: 'الْمُتَكَبِّرُ',
    transliteration: 'Al-Mutakabbir',
    meaning: 'The Majestic / The Supreme',
    explanation: 'He who alone possesses true greatness, transcendent above all creation.',
    foundInQuran: 'Surah Al-Hashr 59:23',
  },
  {
    number: 11,
    arabic: 'الْخَالِقُ',
    transliteration: 'Al-Khāliq',
    meaning: 'The Creator',
    explanation: 'He who brings everything into existence from absolute non-existence with flawless design.',
    foundInQuran: 'Surah Ar-Ra\'d 13:16',
  },
  {
    number: 12,
    arabic: 'الْبَارِئُ',
    transliteration: 'Al-Bāri\'',
    meaning: 'The Maker / Evolver',
    explanation: 'He who crafts things in perfect harmony and proportions, free from disproportion.',
    foundInQuran: 'Surah Al-Hashr 59:24',
  },
  {
    number: 13,
    arabic: 'الْمُصَوِّرُ',
    transliteration: 'Al-Muṣawwir',
    meaning: 'The Fashioner of Forms',
    explanation: 'He who shapes every entity with distinct features, beauty, and unique identity.',
    foundInQuran: 'Surah Al-Hashr 59:24',
  },
  {
    number: 14,
    arabic: 'الْغَفَّارُ',
    transliteration: 'Al-Ghaffār',
    meaning: 'The Perpetual Forgiver',
    explanation: 'He who veils sins repeatedly and forgives again and again upon repentance.',
    foundInQuran: 'Surah Taha 20:82',
  },
  {
    number: 15,
    arabic: 'الْقَهَّارُ',
    transliteration: 'Al-Qahhār',
    meaning: 'The Subduer',
    explanation: 'The Supreme Dominant before whose grandeur all tyrants and creations submit.',
    foundInQuran: 'Surah Yusuf 12:39',
  },
  {
    number: 16,
    arabic: 'الْوَهَّابُ',
    transliteration: 'Al-Wahhāb',
    meaning: 'The Supreme Bestower',
    explanation: 'He who gives abundantly, generously, and ceaselessly without expecting return.',
    foundInQuran: 'Surah Sad 38:35',
  },
  {
    number: 17,
    arabic: 'الرَّزَّاقُ',
    transliteration: 'Ar-Razzāq',
    meaning: 'The Total Provider',
    explanation: 'The Creator of all provision, sustaining the bodies, souls, and intellects of creation.',
    foundInQuran: 'Surah Adh-Dhariyat 51:58',
  },
  {
    number: 18,
    arabic: 'الْفَتَّاحُ',
    transliteration: 'Al-Fattāḥ',
    meaning: 'The Opener / The Reliever',
    explanation: 'He who opens the doors of mercy, guidance, victory, and solutions to locked difficulties.',
    foundInQuran: 'Surah Saba 34:26',
  },
  {
    number: 19,
    arabic: 'الْعَلِيمُ',
    transliteration: 'Al-\'Alīm',
    meaning: 'The All-Knowing',
    explanation: 'He whose knowledge encompasses the past, present, future, and every secret in existence.',
    foundInQuran: 'Surah Al-Baqarah 2:115',
  },
  {
    number: 20,
    arabic: 'الْقَابِضُ',
    transliteration: 'Al-Qābiḍ',
    meaning: 'The Withholder',
    explanation: 'He who restrains sustenance and life according to divine wisdom and purpose.',
    foundInQuran: 'Surah Al-Baqarah 2:245',
  },
  {
    number: 21,
    arabic: 'الْبَاسِطُ',
    transliteration: 'Al-Bāsiṭ',
    meaning: 'The Expander',
    explanation: 'He who broadens sustenance, spirits, and joy for His servants.',
    foundInQuran: 'Surah Ash-Shura 42:27',
  },
  {
    number: 22,
    arabic: 'السَّمِيعُ',
    transliteration: 'As-Samī\'',
    meaning: 'The All-Hearing',
    explanation: 'He who hears every whisper, silent thought, prayer, and declaration throughout the cosmos.',
    foundInQuran: 'Surah Al-Baqarah 2:256',
  },
  {
    number: 23,
    arabic: 'الْبَصِيرُ',
    transliteration: 'Al-Baṣīr',
    meaning: 'The All-Seeing',
    explanation: 'He from whose divine sight nothing is concealed, even a black ant on a black stone in the dark night.',
    foundInQuran: 'Surah Al-Hujurat 49:18',
  },
  {
    number: 24,
    arabic: 'الْحَكِيمُ',
    transliteration: 'Al-Ḥakīm',
    meaning: 'The All-Wise',
    explanation: 'He whose decrees and works are founded upon supreme perfection and eternal wisdom.',
    foundInQuran: 'Surah Al-Baqarah 2:129',
  },
  {
    number: 25,
    arabic: 'الْوَدُودُ',
    transliteration: 'Al-Wadūd',
    meaning: 'The Most Loving',
    explanation: 'The Source of pure love, who loves His righteous servants and is beloved by them.',
    foundInQuran: 'Surah Al-Buruj 85:14',
  },
  {
    number: 26,
    arabic: 'الْحَيُّ',
    transliteration: 'Al-Ḥayy',
    meaning: 'The Ever-Living',
    explanation: 'The eternally living who has neither beginning nor end, upon whom all existence depends.',
    foundInQuran: 'Surah Al-Baqarah 2:255',
  },
  {
    number: 27,
    arabic: 'الْقَيُّومُ',
    transliteration: 'Al-Qayyūm',
    meaning: 'The Self-Sustaining Sustainer',
    explanation: 'He who exists independently and continuously sustains the existence of all that exists.',
    foundInQuran: 'Surah Al-Baqarah 2:255',
  },
  {
    number: 28,
    arabic: 'النُّورُ',
    transliteration: 'An-Nūr',
    meaning: 'The Light',
    explanation: 'The Light of the heavens and the earth, who illuminates hearts with divine guidance.',
    foundInQuran: 'Surah An-Nur 24:35',
  },
  {
    number: 29,
    arabic: 'الْهَادِي',
    transliteration: 'Al-Hādī',
    meaning: 'The Guide',
    explanation: 'He who guides hearts toward the straight path of salvation, truth, and righteousness.',
    foundInQuran: 'Surah Al-Hajj 22:54',
  },
  {
    number: 30,
    arabic: 'الصَّبُورُ',
    transliteration: 'Aṣ-Ṣabūr',
    meaning: 'The Most Patient',
    explanation: 'He who does not rush punishment, showing patient forbearance towards creation.',
    foundInQuran: 'Traditional Sunnah Collection',
  },
];
