import { RabbanaDua } from '../types';

export const RABBANA_DUAS: RabbanaDua[] = [
  {
    id: 1,
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    ayahNumber: 127,
    arabic: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Rabbanā taqabbal minnā innaka antas-Samī\'ul-\'Alīm',
    translation: 'Our Lord, accept [this] from us. Indeed You are the Hearing, the Knowing.',
    significance: 'Supplication made by Prophet Ibrahim and Ismail (AS) when raising the foundations of the Holy Kaaba.',
  },
  {
    id: 2,
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    ayahNumber: 128,
    arabic: 'رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِن ذُرِّيَّتِنَا أُمَّةً مُّسْلِمَةً لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبْ عَلَيْنَا إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ',
    transliteration: 'Rabbanā waj\'alnā muslimayni laka wa min dhurriyyatinā ummatan muslimatan laka wa arinā manāsikanā wa tub \'alaynā innaka antat-Tawwābur-Raḥīm',
    translation: 'Our Lord, make us submissive to You and of our descendants a Muslim community submissive to You. Show us our ways of worship and accept our repentance. Indeed, You are the Accepting of Repentance, the Merciful.',
    significance: 'Supplication for righteous progeny and true devotion.',
  },
  {
    id: 3,
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    ayahNumber: 201,
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Rabbanā ātinā fid-dunyā ḥasanatan wa fil-ākhirati ḥasanatan wa qinā \'adhāban-nār',
    translation: 'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.',
    significance: 'The most comprehensive and frequently recited dua by Prophet Muhammad (ﷺ).',
  },
  {
    id: 4,
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    ayahNumber: 250,
    arabic: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
    transliteration: 'Rabbanā afrigh \'alaynā ṣabran wa thabbit aqdāmanā wanṣurnā \'alal-qawmil-kāfirīn',
    translation: 'Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.',
    significance: 'Dua of Talut\'s army confronting Jalut, asking for steadfastness in trials.',
  },
  {
    id: 5,
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    ayahNumber: 286,
    arabic: 'رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا',
    transliteration: 'Rabbanā lā tu\'ākhidhnā in nasīnā aw akhṭa\'nā',
    translation: 'Our Lord, do not impose blame upon us if we have forgotten or erred.',
    significance: 'From the concluding verses of Surah Al-Baqarah, given as a special blessing.',
  },
  {
    id: 6,
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    ayahNumber: 286,
    arabic: 'رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا',
    transliteration: 'Rabbanā wa lā taḥmil \'alaynā iṣran kamā ḥamaltahū \'alalladhīna min qablinā',
    translation: 'Our Lord, and lay not upon us a burden like that which You laid upon those from before us.',
    significance: 'Supplication for relief from undue hardship.',
  },
  {
    id: 7,
    surahNumber: 2,
    surahName: 'Al-Baqarah',
    ayahNumber: 286,
    arabic: 'رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
    transliteration: 'Rabbanā wa lā tuḥammilnā mā lā ṭāqata lanā bih, wa\'fu \'annā waghfir lanā warḥamnā, Anta mawlānā fanṣurnā \'alal-qawmil-kāfirīn',
    translation: 'Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people.',
    significance: 'Seals the night with divine guardianship and mercy.',
  },
  {
    id: 8,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 8,
    arabic: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ',
    transliteration: 'Rabbanā lā tuzigh qulūbanā ba\'da idh hadaytanā wa hab lanā mil-ladunka raḥmah, innaka antal-Wahhāb',
    translation: 'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.',
    significance: 'Essential prayer for safeguarding faith and protecting against spiritual deviation.',
  },
  {
    id: 9,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 9,
    arabic: 'رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ',
    transliteration: 'Rabbanā innaka jāmi\'un-nāsi liyawmil-lā rayba fīh, innallāha lā yukhliful-mī\'ād',
    translation: 'Our Lord, surely You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise.',
    significance: 'Affirming faith in the Day of Judgment.',
  },
  {
    id: 10,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 16,
    arabic: 'رَبَّنَا إِنَّنَا آمَنَّا فَاغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Rabbanā innanā āmannā faghfir lanā dhunūbanā wa qinā \'adhāban-nār',
    translation: 'Our Lord, indeed we have believed, so forgive us our sins and protect us from the punishment of the Fire.',
    significance: 'Seeking forgiveness on the merit of sincere faith.',
  },
  {
    id: 11,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 53,
    arabic: 'رَبَّنَا آمَنَّا بِمَا أَنزَلْتَ وَاتَّبَعْنَا الرَّسُولَ فَاكْتُبْنَا مَعَ الشَّاهِدِينَ',
    transliteration: 'Rabbanā āmannā bimā anzalta wattaba\'nar-Rasūla faktubnā ma\'ash-shāhidīn',
    translation: 'Our Lord, we have believed in what You revealed and have followed the messenger, so register us among the witnesses.',
    significance: 'Declaration of loyalty to Allah\'s revelation and the Messenger.',
  },
  {
    id: 12,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 191,
    arabic: 'رَبَّنَا مَا خَلَقْتَ هَٰذَا بَاطِلًا سُبْحَانَكَ فَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Rabbanā mā khalaqta hādhā bāṭilā, subḥānaka faqinā \'adhāban-nār',
    translation: 'Our Lord, You did not create this aimlessly; exalted are You [above such a thing]; then protect us from the punishment of the Fire.',
    significance: 'Uttered by people of deep reflection upon contemplating the heavens and earth.',
  },
  {
    id: 13,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 192,
    arabic: 'رَبَّنَا إِنَّكَ مَن تُدْخِلِ النَّارَ فَقَدْ أَخْزَيْتَهُ وَمَا لِلظَّالِمِينَ مِنْ أَنصَارٍ',
    transliteration: 'Rabbanā innaka man tudkhilin-nāra faqad akhzaytah, wa mā liẓ-ẓālimīna min anṣār',
    translation: 'Our Lord, indeed whoever You admit to the Fire - You have disgraced him, and for the wrongdoers there are no helpers.',
    significance: 'Seeking protection from public and eternal humiliation.',
  },
  {
    id: 14,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 193,
    arabic: 'رَّبَّنَا إِنَّنَا سَمِعْنَا مُنَادِيًا يُنَادِي لِلْإِيمَانِ أَنْ آمِنُوا بِرَبِّكُمْ فَآمَنَّا رَبَّنَا فَاغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا وَتَوَفَّنَا مَعَ الْأَبْرَارِ',
    transliteration: 'Rabbanā innanā sami\'nā munādiyan yunādī lil-īmāni an āminū bi-Rabbikum fa-āmannā, Rabbanā faghfir lanā dhunūbanā wa kaffir \'annā sayyi\'ātinā wa tawaffanā ma\'al-abrār',
    translation: 'Our Lord, indeed we have heard a caller calling to faith, [saying], "Believe in your Lord," and we have believed. Our Lord, so forgive us our sins and remove from us our misdeeds and cause us to die with the righteous.',
    significance: 'Recited by the Prophet (ﷺ) upon waking during the night.',
  },
  {
    id: 15,
    surahNumber: 3,
    surahName: 'Ali \'Imran',
    ayahNumber: 194,
    arabic: 'رَبَّنَا وَآتِنَا مَا وَعَدتَّنَا عَلَىٰ رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ الْقِيَامَةِ إِنَّكَ لَا تُخْلِفُ الْمِيعَادَ',
    transliteration: 'Rabbanā wa ātinā mā wa\'adtanā \'alā rusulika wa lā tukhzinā yawmal-qiyāmah, innaka lā yukhliful-mī\'ād',
    translation: 'Our Lord, and grant us what You promised us through Your messengers and do not disgrace us on the Day of Resurrection. Indeed, You do not fail in [Your] promise.',
    significance: 'Pleading for the divine promises conveyed through the prophets.',
  },
  {
    id: 16,
    surahNumber: 7,
    surahName: 'Al-A\'raf',
    ayahNumber: 23,
    arabic: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    transliteration: 'Rabbanā ẓalamnā anfusanā wa in lam taghfir lanā wa tarḥamnā lanakūnanna minal-khāsirīn',
    translation: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    significance: 'The primordial repentance of Adam and Hawwa (peace be upon them).',
  },
  {
    id: 17,
    surahNumber: 7,
    surahName: 'Al-A\'raf',
    ayahNumber: 126,
    arabic: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ',
    transliteration: 'Rabbanā afrigh \'alaynā ṣabran wa tawaffanā muslimīn',
    translation: 'Our Lord, pour upon us patience and let us die as Muslims [in submission to You].',
    significance: 'Supplication of the magicians of Pharaoh after embracing faith under threat of death.',
  },
  {
    id: 18,
    surahNumber: 10,
    surahName: 'Yunus',
    ayahNumber: 85,
    arabic: 'رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ الظَّالِمِينَ وَنَجِّنَا بِرَحْمَتِكَ مِنَ الْقَوْمِ الْكَافِرِينَ',
    transliteration: 'Rabbanā lā taj\'alnā fitnatan lil-qawmiẓ-ẓālimīn, wa najjinā bi-raḥmatika minal-qawmil-kāfirīn',
    translation: 'Our Lord, make us not [objects of] trial for the wrongdoing people, and save us by Your mercy from the disbelieving people.',
    significance: 'Prayer of the companions of Prophet Musa (AS) when oppressed.',
  },
  {
    id: 19,
    surahNumber: 14,
    surahName: 'Ibrahim',
    ayahNumber: 38,
    arabic: 'رَبَّنَا إِنَّكَ تَعْلَمُ مَا نُخْفِي وَمَا نُعْلِنُ وَمَا يَخْفَىٰ عَلَى اللَّهِ مِن شَيْءٍ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ',
    transliteration: 'Rabbanā innaka ta\'lamu mā nukhfī wa mā nu\'lin, wa mā yakhfā \'alallāhi min shay\'in fil-arḍi wa lā fis-samā\'',
    translation: 'Our Lord, indeed You know what we conceal and what we declare, and nothing is hidden from Allah on the earth or in the heaven.',
    significance: 'Prayer of Ibrahim (AS) acknowledging Allah\'s infinite knowledge.',
  },
  {
    id: 20,
    surahNumber: 14,
    surahName: 'Ibrahim',
    ayahNumber: 40,
    arabic: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ',
    transliteration: 'Rabbij-\'alnī muqīmaṣ-ṣalāti wa min dhurriyyatī, Rabbanā wa taqabbal du\'ā\'',
    translation: 'My Lord, make me an establisher of prayer, and [many] from my descendants. Our Lord, and accept my supplication.',
    significance: 'Essential daily dua for steadfastness in prayer for oneself and children.',
  },
  {
    id: 21,
    surahNumber: 14,
    surahName: 'Ibrahim',
    ayahNumber: 41,
    arabic: 'رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ',
    transliteration: 'Rabbanagh-fir lī wa li-wālidayya wa lil-mu\'minīna yawma yaqūmul-ḥisāb',
    translation: 'Our Lord, forgive me and my parents and the believers the Day the account is established.',
    significance: 'Recited at the end of every Salah before the Tasleem.',
  },
  {
    id: 22,
    surahNumber: 18,
    surahName: 'Al-Kahf',
    ayahNumber: 10,
    arabic: 'رَبَّنَا آتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا',
    transliteration: 'Rabbanā ātinā mil-ladunka raḥmatan wa hayyi\' lanā min amrinā rashadā',
    translation: 'Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.',
    significance: 'Dua of the youth of the Cave (Ashab al-Kahf) seeking divine shelter and clarity.',
  },
  {
    id: 23,
    surahNumber: 23,
    surahName: 'Al-Mu\'minun',
    ayahNumber: 109,
    arabic: 'رَبَّنَا آمَنَّا فَاغْفِرْ لَنَا وَارْحَمْنَا وَأَنتَ خَيْرُ الرَّاحِمِينَ',
    transliteration: 'Rabbanā āmannā faghfir lanā warḥamnā wa Anta khayrur-rāḥimīn',
    translation: 'Our Lord, we have believed, so forgive us and have mercy upon us, and You are the best of the merciful.',
    significance: 'Supplication of the humble believers who invoked Allah\'s mercy.',
  },
  {
    id: 24,
    surahNumber: 25,
    surahName: 'Al-Furqan',
    ayahNumber: 65,
    arabic: 'رَبَّنَا اصْرِفْ عَنَّا عَذَابَ جَهَنَّمَ إِنَّ عَذَابَهَا كَانَ غَرَامًا',
    transliteration: 'Rabbanaṣ-rif \'annā \'adhāba jahannama inna \'adhābahā kāna gharāmā',
    translation: 'Our Lord, avert from us the punishment of Hell. Indeed, its punishment is ever adhering.',
    significance: 'Supplication of the \'Ibad ar-Rahman (Servants of the Most Merciful).',
  },
  {
    id: 25,
    surahNumber: 25,
    surahName: 'Al-Furqan',
    ayahNumber: 74,
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    transliteration: 'Rabbanā hab lanā min azwājinā wa dhurriyyātinā qurrata a\'yunin waj\'alnā lil-muttaqīna imāmā',
    translation: 'Our Lord, grant us from among our spouses and offspring comfort to our eyes and make us an example for the righteous.',
    significance: 'The golden supplication for marital peace, beloved children, and leadership in virtue.',
  },
  {
    id: 26,
    surahNumber: 59,
    surahName: 'Al-Hashr',
    ayahNumber: 10,
    arabic: 'رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ وَلَا تَجْعَلْ فِي قُلُوبِنَا غِلًّا لِّلَّذِينَ آمَنُوا رَبَّنَا إِنَّكَ رَءُوفٌ رَّحِيمٌ',
    transliteration: 'Rabbanagh-fir lanā wa li-ikhwāninalladhīna sabaqūnā bil-īmāni wa lā taj\'al fī qulūbinā ghillal-lilladhīna āmanū, Rabbanā innaka Ra\'ūfur-Raḥīm',
    translation: 'Our Lord, forgive us and our brothers who preceded us in faith and put not in our hearts [any] resentment toward those who have believed. Our Lord, indeed You are Kind and Merciful.',
    significance: 'Cleansing the heart of envy, malice, and grievance toward fellow believers.',
  },
  {
    id: 27,
    surahNumber: 60,
    surahName: 'Al-Mumtahanah',
    ayahNumber: 4,
    arabic: 'رَّبَّنَا عَلَيْكَ تَوَكَّلْنَا وَإِلَيْكَ أَنَبْنَا وَإِلَيْكَ الْمَصِيرُ',
    transliteration: 'Rabbanā \'alayka tawakkalnā wa ilayka anabnā wa ilaykal-maṣīr',
    translation: 'Our Lord, upon You we have relied, and to You we have returned, and to You is the destination.',
    significance: 'Pure reliance (Tawakkul) and surrender to Allah alone.',
  },
  {
    id: 28,
    surahNumber: 60,
    surahName: 'Al-Mumtahanah',
    ayahNumber: 5,
    arabic: 'رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلَّذِينَ كَفَرُوا وَاغْفِرْ لَنَا رَبَّنَا إِنَّكَ أَنتَ الْعَزِيزُ الْحَكِيمُ',
    transliteration: 'Rabbanā lā taj\'alnā fitnatan lilladhīna kafarū waghfir lanā, Rabbanā innaka antal-\'Azīzul-Ḥakīm',
    translation: 'Our Lord, make us not [objects of] torment for the disbelievers and forgive us, our Lord. Indeed, it is You who is the Exalted in Might, the Wise.',
    significance: 'Asking that our shortcomings do not push others away from the truth.',
  },
  {
    id: 29,
    surahNumber: 66,
    surahName: 'At-Tahrim',
    ayahNumber: 8,
    arabic: 'رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Rabbanā atmim lanā nūranā waghfir lanā, innaka \'alā kulli shay\'in Qadīr',
    translation: 'Our Lord, perfect for us our light and forgive us. Indeed, You are over all things competent.',
    significance: 'Supplication of the believers crossing the Sirat on the Day of Judgment.',
  },
  {
    id: 30,
    surahNumber: 21,
    surahName: 'Al-Anbiya',
    ayahNumber: 87,
    arabic: 'لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
    transliteration: 'Lā ilāha illā Anta subḥānaka innī kuntu minaẓ-ẓālimīn',
    translation: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    significance: 'Ayat Yunus (Dua al-Karbi). The Prophet (ﷺ) said: No Muslim supplication with this in distress except that Allah responds.',
  },
];
